; ----------------------------------------------------------------------------
; data/background.s — Top logo bitmap + palette
; ----------------------------------------------------------------------------
; Generated by tools/png2planar.py from assets/top_logo.png (320x74).
; Produces two files in build/:
;     build/top_logo.pal — 16 big-endian STE palette words (32 bytes)
;     build/top_logo.img — 4-bitplane word-interleaved bitmap (11840 bytes)
;
; Palette is 16 colors. One source color was merged (two near-identical grays)
; to fit ST's 16-slot limit — see the png2planar.py log on conversion.
; ----------------------------------------------------------------------------

TOP_LOGO_WIDTH      equ     320
TOP_LOGO_HEIGHT     equ     74
TOP_LOGO_LINE_B     equ     (TOP_LOGO_WIDTH/8)*4                    ; 160 bytes/line
TOP_LOGO_BYTES      equ     TOP_LOGO_LINE_B*TOP_LOGO_HEIGHT          ; 11840

                    even
top_logo_palette:
                    incbin      'build/top_logo.pal'

                    even
top_logo_bitmap:
                    incbin      'build/top_logo.img'
