; ----------------------------------------------------------------------------
; data/font.s — Font glyph pack + palette (40×34 source, padded to 48×34)
; ----------------------------------------------------------------------------
; Generated by tools/png2font.py from assets/font40x34_c1.png. Each glyph is
; 816 bytes in the layout:
;     34 lines × 3 pwords × 4 plane-words × 2 bytes
; Glyphs are ordered by ASCII code starting at 32 (space), so the byte offset
; for ASCII character C is: (C - 32) * 816.
;
; The .pal file is shipped for P6 when we'll palette-swap at row boundaries.
; In P5 the text renders into the logo's palette — colors will be "close but
; not right" since font and logo don't share indices; fixed in P6.
; ----------------------------------------------------------------------------

                    even
font_bitmap:
                    incbin      'build/font.bin'

                    ; Row palettes — c1 from PNG, c2/c3 manually created with
                    ; same index structure but different gradient colors (5-10)
                    even
font_palette:
font_palette_c1:
                    incbin      'build/font.pal'    ; purple gradient

                    even
font_palette_c2:
                    incbin      'build/font_c2.pal' ; grayscale gradient

                    even
font_palette_c3:
                    incbin      'build/font_c3.pal' ; cyan gradient

                    ; --- Channel B font (fuzion) — remapped to ASCII layout by
                    ; tools/png2font_remap.py. Same 48×34 / 64-glyph geometry, so
                    ; the engine reads it via chan_font_base unchanged. font_b.pal
                    ; is its native grayscale palette (wire to chan_font_pal_* when
                    ; channel B gets its own colors).
                    even
font_bitmap_b:
                    incbin      'build/font_b.bin'

                    ; Channel B font palette: the fuzion glyphs are ~2-tone
                    ; (body on indices 4 & 15 + minor AA), so a solid bright
                    ; ramp renders them as clean white letters — legible and
                    ; visibly distinct from channel A's purple gradient. Index 0
                    ; stays transparent (the per-scanline raster gradient).
                    even
font_palette_b:
                    dc.w    $000
                    dc.w    $777,$777,$777,$777,$777,$777,$777
                    dc.w    $777,$777,$777,$777,$777,$777,$777
