; ----------------------------------------------------------------------------
; data/font.s — Font glyph pack + palette (40×34 source, padded to 48×34)
; ----------------------------------------------------------------------------
; Generated by tools/png2font.py from assets/font40x34_c1.png. Each glyph is
; 816 bytes in the layout:
;     34 lines × 3 pwords × 4 plane-words × 2 bytes
; Glyphs are ordered by ASCII code starting at 32 (space), so the byte offset
; for ASCII character C is: (C - 32) * 816.
;
; The .pal file is shipped for P6 when we'll palette-swap at row boundaries.
; In P5 the text renders into the logo's palette — colors will be "close but
; not right" since font and logo don't share indices; fixed in P6.
; ----------------------------------------------------------------------------

                    even
font_bitmap:
                    incbin      'build/font.bin'

                    ; Row palettes — c1 from PNG, c2/c3 manually created with
                    ; same index structure but different gradient colors (5-10)
                    even
font_palette:
font_palette_c1:
                    incbin      'build/font.pal'    ; purple gradient

                    even
font_palette_c2:
                    incbin      'build/font_c2.pal' ; grayscale gradient

                    even
font_palette_c3:
                    incbin      'build/font_c3.pal' ; cyan gradient
