; ----------------------------------------------------------------------------
; data/gradient.s — Per-scanline palette-0 table (raster gradient)
; ----------------------------------------------------------------------------
; Generated by tools/gradient2raster.py from assets/gradient.png (3×200, we
; sample middle column). The raw 200 words correspond to the 200 visible
; scanlines: entries 0-69 are $0000 (logo area), 70-199 trace blue→red.
;
; With Timer-B event-count driving the raster, pulses only come from the
; Shifter DE line (active during the 200 visible scanlines) — NOT from top
; overscan or vblank. So entry 0 of this table maps directly to visible
; line 0; no leading pad is needed. (Historical HBL-autovector path wanted
; 62 words of leading padding — obsolete under Timer-B.)
;
; Bottom padding keeps walk-off safe in case we fire past the last visible
; line due to timing slack.
; ----------------------------------------------------------------------------

RASTER_LINES        equ     200
RASTER_TABLE_SLOTS  equ     320
RASTER_BOTTOM_PAD   equ     RASTER_TABLE_SLOTS-RASTER_LINES         ; 120

                    even
raster_table:
raster_visible_start:
                    incbin      'build/gradient.raster'
                    dcb.w       RASTER_BOTTOM_PAD, $0000
raster_table_end:

; Address-form of the single palette-swap trigger. Absolute table entry
; (PALETTE_SWAP_ENTRY); HBL handler compares raster_ptr to this and
; installs the font palette when hit.
raster_swap_font    equ     raster_table+PALETTE_SWAP_ENTRY*2
